kind: ConfigMap
apiVersion: v1
metadata:
  name: products-microservice-properties
data:
  spring.data.cassandra.keyspace-name: cronos
  spring.data.cassandra.contact-points: yb-tservers.yb-dev-yb-cluster.svc.cluster.local
  spring.data.cassandra.port: "9042"
  server.port: "8080"
